[package]
name = "ravalione"
version = "0.1.0"
edition = "2018"
authors = ["DevHyperCoder <devan@devhypercoder.com>"]
license = "GPL-3.0" 

[dependencies]
pest = "2.1.3"
pest_derive = "2.0"
lazy_static = "1.2.0"
